strictness: veryhigh
uses:
    - django
test-warnings: true

bandit:
  run: true

mypy:
  run: true
  options:
    strict: true

pep257:
  run: true
  disable:
    - D100
    - D101
    - D102
    - D103
    - D104
    - D105
    - D106
    - D107
    - D212

pylint:
  disable:
    - no-else-return
    - unsubscriptable-object  # False positive with typing

vulture:
  run: true
