# docker-compose up --build web
# docker-compose run web ./manage.py shell
# docker-compose run web sh
services:
  redis:
    image: redis:alpine

  web:
    build:
      dockerfile: web.Dockerfile
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./friendexing:/opt/friendexing
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis

  test:
    build:
      dockerfile: test.Dockerfile
      context: .
    command: python -m unittest -v
    volumes:
      - ./tests:/opt/testfriendexing
    depends_on:
      - web
      - chromium
      - firefox
    environment:
      - REDIS_URL=redis://redis

  chromium:
    image: selenium/standalone-chrome
    ports:
    - "4444:4444"
    volumes:
    - "/dev/shm:/dev/shm"

  firefox:
    image: selenium/standalone-firefox
    ports:
    - "4445:4444"
    volumes:
    - "/dev/shm:/dev/shm"

  qa:
    build:
      dockerfile: qa.Dockerfile
      context: .
    command: prospector
    volumes:
      - .:/opt/qafriendexing
