# docker-compose up --build web
# docker-compose run web ./manage.py shell
# docker-compose run web sh
services:
  redis:
    image: redis:alpine

  web:
    build:
      context: .
      target: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./friendexing:/opt/friendexing/friendexing
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis
      - "SECRET_KEY=d!2^(l8ke+6s02qv2b*5&%q7+-gz#p!(9pds&+fow1rh(%g&&z"
      - ENABLE_EXTRA=1

  coverage:
    build:
      context: .
      target: coverage
    command: coverage run -p --branch manage.py runserver 0.0.0.0:8000 --noreload
    volumes:
      - ./friendexing:/opt/friendexing/friendexing
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis
      - "SECRET_KEY=d!2^(l8ke+6s02qv2b*5&%q7+-gz#p!(9pds&+fow1rh(%g&&z"
      - ENABLE_EXTRA=1

  coveragereport:
    build:
      context: .
      target: coverage
    command: sh report_coverage.sh
    volumes:
      - ./friendexing:/opt/friendexing/friendexing
      - ./tests:/opt/friendexing/tests
      - ./htmlcov:/opt/friendexing/htmlcov
    working_dir: /opt/friendexing

  test:
    build:
      context: .
      target: test
    command: coverage run -p --branch -m unittest -v
    volumes:
      - ./tests:/opt/friendexing/tests
    depends_on:
      - coverage
      - chromium
      - firefox

  chromium:
    image: selenium/standalone-chrome
    ports:
    - "4444:4444"
    volumes:
    - "/dev/shm:/dev/shm"

  firefox:
    image: selenium/standalone-firefox
    ports:
    - "4445:4444"
    volumes:
    - "/dev/shm:/dev/shm"

  lint:
    build:
      context: .
      target: lint
    command: prospector
    volumes:
      - .:/opt/friendexing
    environment:
      - SECRET_KEY=1234
